spring:

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:54321/coffee}
    username: ${DB_USERNAME:fur}
    password: ${DB_PASSWORD:lucis}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: validate
    show-sql: true

  liquibase:
    changeLog: classpath:/db/changelog/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: true
jwt:
  secret: "dmJE6taqskGVdb0gH8yLffqTy3Q86nddfpwtAkfffyeCZyQqUoL"

server:
  error:
    include-message: always