spring:

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:54321/coffee}
    username: ${DB_USERNAME:fur}
    password: ${DB_PASSWORD:lucis}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: validate
    show-sql: true

  liquibase:
    changeLog: classpath:/db/changelog/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: true

jwt:
  expiration: 604800000
  secret: "dmJE6.aqskGV*b0gH8+Lf0qTy3Q86n?@fpw.Ak@:eCZyQqUoL"