version: '3.1'

services:

  pg_db:
    image: "postgres:11"
    restart: always
    environment:
      POSTGRES_PASSWORD: lucis
      POSTGRES_USER: fur
      POSTGRES_DB: coffee
    ports:
      - 54321:5432
    volumes:
      - pg_coffee:/var/lib/postgresql/data

  pg_db_test:
    image: "postgres:11"
    restart: always
    environment:
      POSTGRES_PASSWORD: lucis
      POSTGRES_USER: fur
      POSTGRES_DB: coffee_test
    ports:
      - 54322:5432
    volumes:
      - pg_coffee_test:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  pg_coffee:
  pg_coffee_test: